image:
  file: Dockerfile           # ← uses the image above

tasks:
  - name: Build signed APK
    init: |
      # Tell Gradle where the SDK is for THIS workspace
      echo "sdk.dir=$ANDROID_HOME" > local.properties
      ./gradlew clean assembleRelease
    command: echo "✅ Signed APK → app/build/outputs/apk/release/app-release.apk"

github:
  prebuilds:
    enabled: true            # build once per branch/PR
    imageCache: true         # reuse Docker layers
