tasks:
  - name: Build signed APK
    init: ./gradlew clean assembleRelease
    command: echo "APK built → app/build/outputs/apk/release/app-release.apk"

# New: persist ~/.android & SDK between pre-builds
vscode:
  extensions:
    - phatblat.vscode-adb-interface     # handy, optional

github:
  prebuilds:
    enabled: true
    imageCache: true                    # ← keep layers with the SDK

